function event_queue = config_time(exp)

global cue_dur;
global trial_dur;
global removal_dur;
global isi_dur;
global rest_dur;

time = 0;

event_queue = {};

event_counter = 1;

for block_idx = 1:length(exp.blocks)

    block = exp.blocks{block_idx};

    %cue
    event_queue{end+1} = config_event(event_counter,...
        'cue',...
        block.type,...
        time,...
        0,...
        0);
    event_counter = event_counter + 1;
    time = time + cue_dur;
    
    for trial_idx = 1:length(block.trials)
       
        trial = block.trials{trial_idx};
        
        %target
        event_queue{end+1} = config_event(event_counter,...
            trial.type,...
            trial.motor_target,...
            time,...
            0,...
            trial);
        event_counter = event_counter + 1;
        time = time + trial_dur;

        %removal
        event_queue{end+1} = config_event(event_counter,...
            'removal',...
            trial.motor_target,...
            time,...
            0,...
            trial);
        event_counter = event_counter + 1;
        time = time + removal_dur;
        
        %removal
        event_queue{end+1} = config_event(event_counter,...
            'isi',...
            '+',...
            time,...
            0,...
            0);
        event_counter = event_counter + 1;
        time = time + isi_dur;
        
        
    end
    
    %cue
    event_queue{end+1} = config_event(event_counter,...
        'rest',...
        '+',...
        time,...
        0,...
        0);
    event_counter = event_counter + 1;
    time = time + rest_dur;
    
end