function flip_time = draw_instructions()

global main_window;

Screen('TextSize',main_window,25);

DrawFormattedText(main_window,...
    ['When you see the # symbol, press the button with the circle in ',...
    'it. \n\n',...
    'When you see the % symbol, press the button to the right of the ',...
    'button with the circle in it \n(return to the front for the one ',...
    'to the far right).'],...
    'center',...
    'center',...
    [255,255,255]);

flip_time = Screen('Flip',main_window);

end