function flip_time = draw_instructions()

global main_window;

Screen('TextSize',main_window,25);

DrawFormattedText(main_window,...
    ['When you see the DOWN ARROW, press the buttons corresponding to ',...
    'the box with the circle in it. \n\n\n\n\n\n\n',...
    'When you see the RIGHT ARROW, press the buttons to the RIGHT of ',...
    'the box with the circle in it. \n(NOTE: for the LAST box on the ',...
    'right, press the FIRST button on the left)'],...
    'center',...
    'center',...
    [255,255,255]);

flip_time = Screen('Flip',main_window);

end