function write_event_log(event_object)

global event_log_file;
global event_log_format;

fprintf(event_log_file,event_log_format,...
    [event_object.event,...
    event_object.type,...
    event_object.value,...
    event_object.time]);

end